import {useState} from 'react';
import {Bet,Person,Stake,stakeText} from '../lib/model';
export function Negotiation({bet,people,personId,mutate,busy}:{bet:Bet;people:Person[];personId:string;mutate:(x:any)=>Promise<boolean>;busy:boolean}){
 const [editing,setEditing]=useState(false),[stake,setStake]=useState<Stake>({type:'dare',text:''});const mine=bet.members.find(m=>m.personId===personId),accepted=bet.acceptances.includes(personId),owner=bet.creator_id===personId;
 const all=bet.members.some(m=>m.side==='for')&&bet.members.some(m=>m.side==='against')&&bet.members.every(m=>bet.acceptances.includes(m.personId));
 const send=(action:string,extra:any={})=>mutate({action,id:bet.id,revision:bet.revision,...extra});
 const history=<details><summary>Historique des propositions</summary>{bet.proposals.map(p=><p key={p.revision}><strong>Version {p.revision}</strong> · {people.find(x=>x.id===p.person_id)?.name}<br/>{stakeText(p.stake)}</p>)}</details>;
 if(bet.status!=='active')return bet.proposals.length?<section className="negotiation">{history}</section>:null;
 if(bet.phase==='locked')return <section className="negotiation"><p className="agreement-note">🤝 Pari lancé : les camps et l’enjeu sont fixés.</p>{bet.proposals.length>0&&history}</section>;
 return <section className="negotiation"><h3>🤞 Un pari ouvert à la bande</h3><p className="muted">Choisis ton camp, puis accepte l’enjeu ou propose autre chose. Tu es libre de ne pas participer.</p><div className="actions"><button disabled={busy||mine?.side==='for'} className="secondary" onClick={()=>send('join',{side:'for'})}>👍 {mine?.side==='for'?'Tu es Pour':'Je suis Pour'}</button><button disabled={busy||mine?.side==='against'} className="secondary" onClick={()=>send('join',{side:'against'})}>👎 {mine?.side==='against'?'Tu es Contre':'Je suis Contre'}</button>{mine&&!owner&&<button disabled={busy} className="text-btn" onClick={()=>{if(window.confirm('Quitter ce pari ? Les accords des participants seront à renouveler.'))send('leave');}}>Quitter le pari</button>}</div>
 <h4>Proposition {bet.revision} · {bet.stake.type==='reward'?'Récompense':bet.stake.type==='dare'?'Gage':'Enjeu'}</h4><p className="prewrap">{stakeText(bet.stake)}</p><p className="small-text muted">Toute modification de l’enjeu ou des camps demande un nouvel accord à chacun.</p><ul className="consent-list">{bet.members.map(m=><li key={m.personId}>{people.find(p=>p.id===m.personId)?.name} · {m.side==='for'?'Pour':'Contre'} <span>{bet.acceptances.includes(m.personId)?'✓ Accepté':'En attente'}</span></li>)}</ul>
 {mine&&<><div className="actions"><button className={accepted?'secondary':'primary'} disabled={busy} onClick={()=>send(accepted?'withdraw':'accept')}>{accepted?'Retirer mon accord':'Accepter cet enjeu'}</button><button className="secondary" disabled={busy} onClick={()=>{setEditing(!editing);setStake(bet.stake);}}>Faire une contre-proposition</button></div>{editing&&<form className="proposal-form" onSubmit={async e=>{e.preventDefault();if(await send('propose',{stake}))setEditing(false);}}><label className="field">Type d’enjeu<select value={stake.type} onChange={e=>setStake(e.target.value==='money'?{type:'money',amount:20,currency:'EUR'}:{type:e.target.value as Stake['type'],text:''})}><option value="dare">Gage pour les perdants</option><option value="reward">Récompense pour les gagnants</option><option value="money">Argent (sans paiement)</option><option value="other">Autre engagement</option><option value="none">Aucun enjeu</option></select></label>{stake.type==='money'?<div className="two-fields"><label className="field">Montant<input required type="number" min="0.01" step="0.01" value={stake.amount||''} onChange={e=>setStake({...stake,amount:Number(e.target.value)})}/></label><label className="field">Devise<select value={stake.currency} onChange={e=>setStake({...stake,currency:e.target.value})}>{['EUR','XPF','USD'].map(c=><option key={c}>{c}</option>)}</select></label></div>:stake.type!=='none'&&<label className="field">Qui fait ou offre quoi, à qui ?<textarea required maxLength={500} value={stake.text||''} onChange={e=>setStake({...stake,text:e.target.value})} placeholder="Les perdants offrent un dîner aux gagnants."/></label>}<p className="small-text muted">En proposant cet enjeu, tu l’acceptes. Les autres participants devront donner leur accord.</p><button className="primary" disabled={busy}>Soumettre ma proposition</button></form>}</>}
 {owner&&<><p className="small-text muted">Lance le pari quand tout le monde est prêt. Après confirmation, personne ne pourra rejoindre ni changer l’enjeu.</p><button className="primary full" disabled={busy||!all} onClick={()=>{if(window.confirm('Lancer le pari avec ces participants et cet enjeu ? Les conditions seront fixées.'))send('lock');}}>Lancer le pari avec l’accord de tous</button></>}
 {history}</section>;
}
export function PasswordSettings(){const [currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="panel"><summary>Modifier mon mot de passe</summary><form onSubmit={async e=>{e.preventDefault();setError('');if(password!==confirm){setError('Les mots de passe ne correspondent pas.');return;}setBusy(true);try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'password',currentPassword,password})});const d=await r.json();if(!r.ok)throw Error(d.error);location.reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Mot de passe actuel<input required type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label className="field">Nouveau mot de passe<input required minLength={12} maxLength={256} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field">Confirmer<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="small-text muted">Tu devras te reconnecter sur tes appareils.</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>Enregistrer le nouveau mot de passe</button></form></details>;}
