import {useState} from 'react';
import {Bet,Person,Stake,stakeText} from '../lib/model';
const stakeKinds:[Stake['type'],string][]=[['dare','🎯 Gage'],['reward','🎁 Récompense'],['money','💰 Argent'],['other','✨ Autre'],['none','🤝 Pour le plaisir']];
export function Negotiation({bet,people,personId,mutate,busy}:{bet:Bet;people:Person[];personId:string;mutate:(x:any)=>Promise<boolean>;busy:boolean}){
 const [editing,setEditing]=useState(false),[stake,setStake]=useState<Stake>({type:'dare',text:''}),[targets,setTargets]=useState<string[]>([]),[draftRevision,setDraftRevision]=useState(bet.revision);
 const mine=bet.members.find(m=>m.personId===personId),active=bet.status==='active',owner=bet.creator_id===personId;
 const deals=bet.deals||[],accepted=deals.filter(d=>d.status==='accepted'),pending=deals.filter(d=>d.status==='pending'),history=deals.filter(d=>!['accepted','pending'].includes(d.status));
 const opponents=bet.members.filter(m=>mine&&m.side!==mine.side),name=(id:string)=>people.find(p=>p.id===id)?.name||'Ancien participant';
 const send=(action:string,extra:any={})=>mutate({action,id:bet.id,revision:bet.revision,...extra});
 const canStart=bet.members.some(m=>m.side==='for')&&bet.members.some(m=>m.side==='against')&&bet.members.every(m=>(!!bet.legacy_agreement&&(bet.legacy_members||[]).includes(m.personId))||accepted.some(d=>d.proposer_id===m.personId||d.recipient_id===m.personId));
 function edit(target?:string,s?:Stake){setTargets(target?[target]:[]);setStake({...s||bet.stake});setDraftRevision(bet.revision);setEditing(true);}
 const expired=!!bet.deadline&&bet.deadline<new Date().toISOString().slice(0,10),canDiscuss=active&&!expired;
 return <section className="negotiation simple-negotiation deals-panel">
 {mine&&<div className={'fixed-camp '+mine.side}><span>{mine.side==='for'?'Tu es Pour':'Tu es Contre'}</span><small>Camp définitif</small></div>}
 {!mine&&active&&bet.phase==='open'&&<div><h3>Tu prends le pari ?</h3><div className="actions">{['for','against'].map(side=><button key={side} className="secondary" disabled={busy} onClick={()=>{if(window.confirm('Rejoindre le camp '+(side==='for'?'Pour':'Contre')+' ? Ce choix est définitif.'))send('join',{side});}}>{side==='for'?'Pour':'Contre'}</button>)}</div></div>}
 <h3>Accords acceptés <span className="muted">{accepted.length+(bet.legacy_agreement?1:0)}</span></h3>
 {bet.legacy_agreement&&<div className="deal-agreed"><small>Accord collectif d’origine</small><strong>{stakeText(bet.legacy_agreement)}</strong><p className="small-text">Conservé pour {(bet.legacy_members||[]).map(name).join(', ')}. Les nouveaux accords individuels s’y ajoutent.</p></div>}
 {!accepted.length&&!bet.legacy_agreement&&<><p className="muted small-text">Aucun engagement pour le moment.</p>{!pending.length&&<p className="small-text muted">Idée de départ, non acceptée : {stakeText(bet.stake)}</p>}</>}
 {accepted.map(d=>{const loser=bet.result==='for'||bet.result==='against'?[d.proposer_id,d.recipient_id].find(id=>bet.members.find(m=>m.personId===id)?.side!==bet.result):undefined;return <article className="deal-agreed" key={d.id}><small>✓ {name(d.proposer_id)} ↔ {name(d.recipient_id)}</small><strong className="prewrap">{stakeText(d.stake)}</strong>{loser&&d.stake.type!=='none'&&<p className="small-text"><b>{name(loser)}</b> doit honorer cet engagement envers {name(loser===d.proposer_id?d.recipient_id:d.proposer_id)}.</p>}{['cancelled','undetermined'].includes(bet.result||'')&&<p className="small-text">Aucun engagement à exécuter : résultat annulé ou indéterminé.</p>}{canDiscuss&&[d.proposer_id,d.recipient_id].includes(personId)&&<button className="text-btn" disabled={busy} onClick={()=>edit(d.proposer_id===personId?d.recipient_id:d.proposer_id,d.stake)}>Proposer une modification</button>}</article>})}
 {canDiscuss&&mine&&!editing&&<button className="secondary full" disabled={busy||!opponents.length} onClick={()=>edit()}>+ Proposer un accord</button>}
 {active&&mine&&!opponents.length&&<p className="small-text muted">Un adversaire doit rejoindre le pari pour recevoir une proposition.</p>}
 {editing&&canDiscuss&&<form className="proposal-form" onSubmit={async e=>{e.preventDefault();if(await send('dealPropose',{stake,recipients:targets,revision:draftRevision}))setEditing(false);}}><h3>Nouvelle proposition</h3><fieldset className="deal-targets"><legend>À qui ?</legend><button type="button" className="text-btn" onClick={()=>setTargets(opponents.map(m=>m.personId))}>Tous les adversaires</button>{opponents.map(m=><label key={m.personId}><input type="checkbox" checked={targets.includes(m.personId)} onChange={e=>setTargets(e.target.checked?[...targets,m.personId]:targets.filter(id=>id!==m.personId))}/>{name(m.personId)}</label>)}</fieldset>
<div className="stake-kind-choices" role="group" aria-label="Type d’enjeu">{stakeKinds.map(([type,label])=><button type="button" key={type} aria-pressed={stake.type===type} className={stake.type===type?'chosen':''} onClick={()=>setStake(type==='money'?{type,amount:20,currency:'EUR'}:{type,text:''})}>{label}</button>)}</div>{stake.type==='money'?<><div className="two-fields"><label className="field">Montant<input required type="number" min="0.01" max="1000000000000" step="0.01" value={stake.amount||''} onChange={e=>setStake({...stake,amount:Number(e.target.value)})}/></label><label className="field">Devise<select value={stake.currency} onChange={e=>setStake({...stake,currency:e.target.value})}>{['EUR','XPF','USD'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="small-text muted">Engagement mémorisé, sans paiement dans l’application.</p></>:stake.type!=='none'&&<label className="field">{stake.type==='dare'?'Le gage des perdants':stake.type==='reward'?'La récompense des gagnants':'Ton idée'}<textarea autoFocus required maxLength={500} rows={3} value={stake.text||''} onChange={e=>setStake({...stake,text:e.target.value})} placeholder="Les perdants offrent une pizza aux gagnants."/></label>} <p className="small-text muted">Le perdant honore cet enjeu envers le gagnant, pour chaque duo. Chacun répond séparément.</p>
 {targets.some(id=>accepted.some(d=>[d.proposer_id,d.recipient_id].includes(id)&&[d.proposer_id,d.recipient_id].includes(personId)))&&<p className="inline-warning">L’accord actuel reste valable jusqu’à l’acceptation de son remplacement.</p>}
 {targets.some(id=>pending.some(d=>[d.proposer_id,d.recipient_id].includes(id)&&[d.proposer_id,d.recipient_id].includes(personId)))&&<p className="small-text muted">Cette offre remplace la discussion en attente avec les personnes choisies.</p>}
 {draftRevision!==bet.revision&&<p role="alert">Le pari a changé. Ferme puis rouvre la proposition.</p>}
 <div className="actions"><button type="button" className="secondary" onClick={()=>setEditing(false)}>Annuler</button><button className="primary" disabled={busy||!targets.length||draftRevision!==bet.revision}>Envoyer</button></div></form>}
 {pending.length>0&&<><h3>{active?'En discussion':'Propositions non conclues'}</h3><p className="small-text muted">Les accords acceptés restent valables.</p>{pending.map(d=><article className="deal-pending" key={d.id}><small>{name(d.proposer_id)} → {name(d.recipient_id)}</small><strong className="prewrap">{stakeText(d.stake)}</strong><span className="small-text">{d.replaces_id?'Modification proposée':'Nouvel accord proposé'}</span>{canDiscuss&&d.recipient_id===personId&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>{if(window.confirm('Accepter « '+stakeText(d.stake)+' » avec '+name(d.proposer_id)+' ?'+(d.replaces_id?' Cela remplacera votre accord précédent.':'')))send('dealAccept',{dealId:d.id});}}>Accepter</button><button className="secondary" disabled={busy} onClick={()=>send('dealReject',{dealId:d.id})}>Refuser</button><button className="text-btn" disabled={busy} onClick={()=>edit(d.proposer_id,d.stake)}>Contre-proposer</button></div>}{canDiscuss&&d.proposer_id===personId&&<button className="text-btn" disabled={busy} onClick={()=>send('dealWithdraw',{dealId:d.id})}>Retirer la proposition</button>}</article>)}</>}
 {active&&owner&&bet.phase==='open'&&<div className="start-agreement"><p className="small-text muted">Pour lancer : deux camps, et au moins un accord accepté par participant. « Pour le plaisir » compte aussi.</p><button className="primary full" disabled={busy||!canStart} onClick={()=>{if(window.confirm('Lancer le pari et fermer les inscriptions ? Les accords resteront modifiables par consentement mutuel.'))send('lock');}}>Lancer le pari</button></div>}
 {history.length>0&&<details className="proposal-history"><summary>Historique des propositions</summary>{history.map(d=><p key={d.id}><b>{name(d.proposer_id)} ↔ {name(d.recipient_id)}</b><br/>{stakeText(d.stake)} · {d.status==='rejected'?'Refusée':d.status==='withdrawn'?'Retirée':'Remplacée'}</p>)}</details>}
 <details className="agreement-help"><summary>Comment ça marche ?</summary><p>Les camps restent fixes. Chaque duo accepte son propre enjeu. Une proposition à plusieurs personnes crée un accord distinct avec chacune. Tes engagements s’additionnent ; refuser une nouvelle proposition ne retire aucun accord accepté. Les discussions restent possibles après le lancement, jusqu’à la clôture ou la date limite.</p></details>
 </section>;
}
export function PasswordSettings(){const [currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="panel"><summary>Modifier mon mot de passe</summary><form onSubmit={async e=>{e.preventDefault();setError('');if(password!==confirm){setError('Les mots de passe ne correspondent pas.');return;}setBusy(true);try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'password',currentPassword,password})});const d=await r.json();if(!r.ok)throw Error(d.error);location.reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Mot de passe actuel<input required type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label className="field">Nouveau mot de passe<input required minLength={12} maxLength={256} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field">Confirmer<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="small-text muted">Tu devras te reconnecter sur tes appareils.</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>Enregistrer le nouveau mot de passe</button></form></details>;}
