import {runtime} from '../server/runtime';
export const config=()=>runtime();
export const db=()=>{const d=config().DB;if(!d)throw Error('Base de données indisponible');return d;};
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export function sameOrigin(r:Request){const origin=r.headers.get('origin');if(origin && origin!==new URL(r.url).origin)throw Error('Origine non autorisée');}
export async function seed(){const d=db();const exists=await d.prepare("SELECT id FROM groups WHERE id='local'").first();if(exists)return;if(process.env.SEED_DEMO==='false'){await d.prepare("INSERT INTO groups(id,name) VALUES('local','La bande')").run();return;}
const people=[['eva','Eva','👩🏻','#ffe2d5'],['lucas','Lucas','🧑🏽','#e3eaff'],['lea','Léa','👩🏼','#ffe9ac'],['hugo','Hugo','👨🏻','#dff0e5'],['emma','Emma','👩🏽‍🦱','#f1dfff']];
const demo=[{id:'demo-japon',title:'Eva partira vivre au Japon avant 2030',description:'Un séjour de plus de 6 mois, avec une adresse sur place. Un simple voyage ne compte pas !',deadline:'2029-12-31',stake:{type:'dare',text:'Un dîner japonais offert par les perdants'},created:'2026-09-01T08:00:00Z',sides:['for','against','for','against','for'],next:'2027-01-01T08:00:00Z',frequency:'yearly'}, {id:'demo-marathon',title:'Lucas terminera son premier marathon',description:'42,195 km et une photo à l’arrivée. Peu importe le chrono.',deadline:'2027-06-30',stake:{type:'money',amount:5000,currency:'XPF'},created:'2026-09-15T08:00:00Z',sides:['for','for','against','against'],next:'2026-10-01T08:00:00Z',frequency:'monthly'}, {id:'demo-digital',title:'Hugo tiendra un mois sans Instagram',description:'Aucune connexion pendant 30 jours consécutifs.',deadline:'2026-12-01',stake:{type:'dare',text:'Le petit-déjeuner pour toute la bande'},created:'2026-09-20T08:00:00Z',sides:['against','for','for','for'],next:'2026-10-20T08:00:00Z',frequency:'once'}, {id:'demo-surf',title:'Léa réussira à se lever sur une planche de surf',description:'Défi relevé à la plage, témoins à l’appui.',deadline:'2026-08-30',stake:{type:'none'},created:'2026-07-01T08:00:00Z',sides:['for','against','for','against'],result:'for',closed:'2026-08-23T09:00:00Z'}];
const q=[d.prepare("INSERT OR IGNORE INTO groups(id,name) VALUES('local','La bande')"),...people.map(p=>d.prepare('INSERT OR IGNORE INTO participants(id,group_id,name,avatar,color,demo) VALUES(?,?,?,?,?,1)').bind(p[0],'local',p[1],p[2],p[3]))];
for(const b of demo){q.push(d.prepare('INSERT OR IGNORE INTO bets(id,group_id,title,description,deadline,stake,status,result,created,closed,comment,demo) VALUES(?,?,?,?,?,?,?,?,?,?,?,1)').bind(b.id,'local',b.title,b.description,b.deadline,JSON.stringify(b.stake),b.result?'closed':'active',b.result||null,b.created,b.closed||null,b.result?'Trois vagues debout. Pari tenu !':null));b.sides.forEach((side,i)=>q.push(d.prepare('INSERT OR IGNORE INTO members(id,bet_id,person_id,side) VALUES(?,?,?,?)').bind(b.id+'-'+i,b.id,people[i][0],side)));q.push(d.prepare('INSERT OR IGNORE INTO events(id,bet_id,at,text) VALUES(?,?,?,?)').bind(b.id+'-created',b.id,b.created,'Pari de démonstration créé'));if(b.next)q.push(d.prepare('INSERT OR IGNORE INTO reminders(id,bet_id,next,frequency,timezone,anchor) VALUES(?,?,?,?,?,?)').bind(b.id+'-reminder',b.id,b.next,b.frequency,'Pacific/Noumea',b.next));}await d.batch(q);}
export async function readData(){await seed();const d=db();const [p,b,m,r,e]=await Promise.all(['participants','bets','members','reminders','events'].map(t=>d.prepare(`SELECT * FROM ${t}`).all()));const heartbeat=await d.prepare("SELECT value FROM settings WHERE key='scheduler_heartbeat'").first();return {people:p.results,bets:b.results.map((b:any)=>({...b,stake:JSON.parse(b.stake),members:m.results.filter((m:any)=>m.bet_id===b.id).map((m:any)=>({personId:m.person_id,side:m.side})),reminders:r.results.filter((r:any)=>r.bet_id===b.id),events:e.results.filter((e:any)=>e.bet_id===b.id).sort((a:any,b:any)=>b.at.localeCompare(a.at))})),pushConfigured:!!(config().VAPID_PUBLIC_KEY&&config().VAPID_PRIVATE_KEY),schedulerActive:!!heartbeat&&Date.now()-Date.parse(heartbeat.value)<5400000,publicKey:config().VAPID_PUBLIC_KEY||null};}
